eureka:
  client:
    register-with-eureka: false
server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service
          uri: http://localhost:8084
          predicates:
            - Path=/api/users/**

        - id: transaction_service
          uri: http://localhost:8085
          predicates:
            - Path=/api/transactions/**

        - id: car_service
          uri: http://localhost:8086
          predicates:
            - Path=/api/cars/**

